[package]
name = "crox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ariadne = { version = "0.1.5", optional = true }
chumsky = { version = "0.8.0", optional = true }
miette = { version = "5.3.0", optional = true, features = ["fancy"] }
nom = { version = "7.1.1", optional = true }

[features]
default = []
chumsky = ["dep:chumsky", "dep:ariadne"]
nom = ["dep:nom", "dep:miette"]

[profile.release]
codegen-units = 1
debug = false
debug-assertions = false
lto = true
opt-level = 3
overflow-checks = true
rpath = false
strip = true

[dev-dependencies]
pretty_assertions = "1.3.0"
