[package]
name = "crox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ariadne = { version = "0.1.5", optional = true }
chumsky = { version = "0.8.0", optional = true }

[features]
default = []
chumsky = ["dep:chumsky", "dep:ariadne"]

[profile.release]
codegen-units = 1
debug = false
debug-assertions = false
lto = true
opt-level = 3
overflow-checks = true
rpath = false
strip = true
